name: Label Timer Workflow

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  label_timer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Label Timer
        uses: tbsmcd/label_timer@v3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          targets: |
            - label: in progress
              action: comment
            - label: done
              action: comment
            - label: review
              action: comment
            - label: wait review
              action: comment
