name: Start and Stop time tracker

on:
  issues:
    types: [labeled]

jobs:
  everhour_timer_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios @octokit/rest

      - name: Determine action based on label
        run: |
          label="${{ github.event.label.name }}"
          if [[ $label == "in progress" ]]; then
            node .github/scripts/start-everhour-time.mjs
          elif [[ $label == "wait_review" ]]; then
            node .github/scripts/stop-everhour-time.mjs
          else
            echo "No action defined for label: $label"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVERHOUR_API_TOKEN: ${{ secrets.EVERHOUR_API_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PAYLOAD: ${{ toJson(github.event) }}
